#!/usr/bin/env python3
"""claude-pool — round-robin / least-busy multiplexer across multiple
Claude Max accounts.

Each account gets its own isolated profile dir under
$CLAUDE_POOL_ROOT/profile-<N>/. When `claude-pool exec` runs, it picks the
next-due profile and execs `claude` with HOME pointed at that dir, so all
of claude's auth state (.claude/.credentials.json + .claude.json) reads
from THAT account's profile.

Subcommands:
  init [--count N] [--labels ...]
      Create N profile dirs + print login instructions. Idempotent —
      re-running doesn't blow away existing profiles.

  status
      Show each profile's auth state, in-use count, total uses, last
      used timestamp.

  exec -- [claude args...]
      Pick the next-due profile (least in-use, then oldest last-used)
      and exec claude with that profile's HOME. Forwards stdin/stdout
      and the exit code.

Wiring agents:
  Put $CLAUDE_POOL_ROOT/bin/ first on PATH (the init step writes a
  `claude` shim there that delegates to `claude-pool exec`). Existing
  agent code that calls `claude --print ...` automatically routes
  through the pool with zero code changes.

Environment overrides:
  CLAUDE_POOL_ROOT       — base dir (default: ~/.reusable-agents/claude-pool)
  CLAUDE_POOL_REAL_CLAUDE — path to the real claude binary (auto-detected
                            from PATH when unset, excluding the shim)
"""
from __future__ import annotations

import argparse
import fcntl
import json
import os
import re
import shutil
import subprocess
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path


ROOT = Path(os.environ.get("CLAUDE_POOL_ROOT")
            or os.path.expanduser("~/.reusable-agents/claude-pool"))
STATE_FILE = ROOT / "state.json"
SHIM_DIR = ROOT / "bin"
SHIM_PATH = SHIM_DIR / "claude"


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _resolve_real_claude() -> str:
    """Find the real claude binary (not our shim)."""
    explicit = os.environ.get("CLAUDE_POOL_REAL_CLAUDE")
    if explicit and Path(explicit).is_file():
        return explicit
    shim_resolved = SHIM_PATH.resolve() if SHIM_PATH.exists() else None
    for d in (os.environ.get("PATH") or "").split(":"):
        if not d:
            continue
        cand = Path(d) / "claude"
        if not cand.is_file():
            continue
        try:
            if shim_resolved and cand.resolve() == shim_resolved:
                continue
        except Exception:
            pass
        return str(cand)
    raise SystemExit("claude binary not found on PATH (set CLAUDE_POOL_REAL_CLAUDE)")


def _open_state_locked():
    """Open state.json with an exclusive flock. Caller must close + unlock."""
    ROOT.mkdir(parents=True, exist_ok=True)
    fd = os.open(str(STATE_FILE), os.O_RDWR | os.O_CREAT, 0o644)
    fcntl.flock(fd, fcntl.LOCK_EX)
    return fd


def _read_state(fd: int) -> dict:
    try:
        raw = os.pread(fd, 1 << 20, 0).decode() or "{}"
        return json.loads(raw)
    except Exception:
        return {}


def _write_state(fd: int, state: dict) -> None:
    blob = json.dumps(state, indent=2).encode()
    os.ftruncate(fd, 0)
    os.pwrite(fd, blob, 0)


def _close_state(fd: int) -> None:
    try:
        fcntl.flock(fd, fcntl.LOCK_UN)
    finally:
        os.close(fd)


def _is_authenticated(home: str) -> bool:
    return (Path(home) / ".claude" / ".credentials.json").exists()


def _ensure_profile_dir(idx: int, label: str = "") -> Path:
    pdir = ROOT / f"profile-{idx}"
    pdir.mkdir(parents=True, exist_ok=True)
    # Symlink read-mostly user configs so claude's tool calls (git, etc.)
    # see the same identity. We isolate ONLY the Claude auth state.
    real_home = Path(os.path.expanduser("~"))
    for fname in (".gitconfig", ".gitignore_global", ".npmrc", ".bashrc"):
        src = real_home / fname
        dst = pdir / fname
        if src.exists() and not dst.exists() and not dst.is_symlink():
            try:
                dst.symlink_to(src)
            except OSError:
                pass
    return pdir


def _write_shim() -> None:
    """Write a `claude` shim that delegates to `claude-pool exec`. Put
    its parent on PATH ahead of /usr/local/bin/claude to route every
    `claude` call through the pool."""
    SHIM_DIR.mkdir(parents=True, exist_ok=True)
    real = _resolve_real_claude()
    SHIM_PATH.write_text(f"""#!/usr/bin/env bash
# Auto-generated by claude-pool. Routes `claude` calls through the pool.
# Real claude binary: {real}
exec python3 {Path(__file__).resolve()} exec -- "$@"
""")
    SHIM_PATH.chmod(0o755)


# ── Subcommands ──────────────────────────────────────────────────────────

def cmd_init(args) -> None:
    n = args.count
    if n < 1:
        raise SystemExit("--count must be ≥ 1")
    fd = _open_state_locked()
    try:
        state = _read_state(fd)
        for i in range(1, n + 1):
            pdir = _ensure_profile_dir(i)
            key = f"profile-{i}"
            label = ""
            if args.labels and i <= len(args.labels):
                label = args.labels[i - 1]
            state.setdefault(key, {})
            state[key].update({
                "id": key,
                "home": str(pdir),
                "in_use": state[key].get("in_use", 0),
                "last_used_at": state[key].get("last_used_at", ""),
                "total_uses": state[key].get("total_uses", 0),
                "label": label or state[key].get("label", ""),
            })
            state[key]["authenticated"] = _is_authenticated(str(pdir))
        _write_state(fd, state)
    finally:
        _close_state(fd)
    _write_shim()
    print(f"\n✓ {n} profile(s) prepared at {ROOT}/")
    print(f"✓ shim written to {SHIM_PATH}\n")
    print(f"To use the pool, prepend its bin/ on PATH:")
    print(f"  export PATH={SHIM_DIR}:$PATH\n")
    print("─" * 70)
    print("To authenticate each profile, run these one-by-one in a terminal")
    print("with browser access (each opens a Claude OAuth flow in your browser):\n")
    for i in range(1, n + 1):
        pdir = ROOT / f"profile-{i}"
        already = "✓ AUTHED" if _is_authenticated(str(pdir)) else "  needs auth"
        real = _resolve_real_claude()
        print(f"  [{already}]  HOME={pdir} {real} /login")
    print("\nAfter logging in to each profile, run:  claude-pool status")
    print("─" * 70)


def cmd_status(args) -> None:
    fd = _open_state_locked()
    try:
        state = _read_state(fd)
        # Refresh authenticated flag from disk
        for p in state.values():
            p["authenticated"] = _is_authenticated(p.get("home", ""))
        _write_state(fd, state)
    finally:
        _close_state(fd)
    if not state:
        print("No profiles configured. Run: claude-pool init --count N")
        return
    print(f"{'PROFILE':<12}  {'AUTH':<5} {'STATE':<14} {'IN_USE':<7} {'TOTAL':<6} {'LAST_USED':<22}  LABEL / NOTES")
    print("-" * 100)
    for k in sorted(state.keys()):
        p = state[k]
        auth = "✓" if p.get("authenticated") else "—"
        last = p.get("last_used_at") or "-"
        if not p.get("authenticated"):
            state_str = "no-auth"
        elif _is_rate_limited_now(p):
            state_str = f"rate-limited"
            resets_at = p.get("limit_resets_at", "")[:19]
            label_extra = f" — resets {resets_at}"
        else:
            state_str = "ready"
            label_extra = ""
        if state_str != "rate-limited":
            label_extra = ""
        print(f"{p['id']:<12}  {auth:<5} {state_str:<14} {p.get('in_use',0):<7} {p.get('total_uses',0):<6} {last:<22}  {p.get('label','')}{label_extra}")


def _is_rate_limited_now(p: dict) -> bool:
    """Check if a profile's stored `limit_resets_at` is still in the future."""
    rs = p.get("limit_resets_at") or ""
    if not rs:
        return False
    try:
        when = datetime.fromisoformat(rs.replace("Z", "+00:00"))
        return datetime.now(timezone.utc) < when
    except Exception:
        return False


def _pick_profile(state: dict, exclude_ids: set | None = None) -> dict | None:
    """Return the next profile to dispatch to, or None if nothing eligible.

    Eligibility (in order):
      1. authenticated (cred file on disk)
      2. NOT currently rate-limited (limit_resets_at in the future)
      3. not in exclude_ids (used by failover loop to avoid re-picking
         the same just-failed profile in this same call)

    Pick policy: lowest in_use, then oldest last_used_at, then id.
    """
    excl = exclude_ids or set()
    eligible = [
        p for p in state.values()
        if _is_authenticated(p.get("home", ""))
        and not _is_rate_limited_now(p)
        and p.get("id") not in excl
    ]
    if not eligible:
        return None
    eligible.sort(key=lambda p: (p.get("in_use", 0),
                                 p.get("last_used_at", ""),
                                 p.get("id", "")))
    return eligible[0]


# Patterns that indicate the picked account is rate-limited and we should
# fail over to a different one. Captured from claude's actual error message:
#   "You've hit your limit · resets 10pm (America/Detroit)"
#   "5-hour usage limit reached" / similar variants from API quotas.
_RATE_LIMIT_PATTERNS = [
    re.compile(r"hit your limit", re.I),
    re.compile(r"usage limit reached", re.I),
    re.compile(r"rate limit", re.I),
    re.compile(r"quota exceeded", re.I),
    re.compile(r"too many requests", re.I),
]
# Capture the human reset hint so we can store an approximate resets_at.
_RESET_HINT_RE = re.compile(r"resets?\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\s*(?:\(([^)]+)\))?", re.I)


def _parse_reset_at(text: str) -> str | None:
    """Best-effort parse of "resets 10pm (America/Detroit)" → next 10pm in
    that timezone, expressed as a UTC ISO timestamp. If parsing fails,
    return None and the caller falls back to a fixed-offset default."""
    m = _RESET_HINT_RE.search(text or "")
    if not m:
        return None
    hour = int(m.group(1))
    minute = int(m.group(2) or 0)
    ampm = (m.group(3) or "").lower()
    tzname = (m.group(4) or "").strip()
    if ampm == "pm" and hour < 12:
        hour += 12
    if ampm == "am" and hour == 12:
        hour = 0
    try:
        try:
            from zoneinfo import ZoneInfo
            tz = ZoneInfo(tzname) if tzname else timezone.utc
        except Exception:
            tz = timezone.utc
        now_local = datetime.now(tz)
        reset = now_local.replace(hour=hour, minute=minute, second=0, microsecond=0)
        if reset <= now_local:
            reset = reset + timedelta(days=1)
        return reset.astimezone(timezone.utc).isoformat(timespec="seconds")
    except Exception:
        return None


def _mark_rate_limited(profile_id: str, captured_text: str) -> None:
    """Record limit_resets_at on the profile so subsequent picks skip it."""
    parsed = _parse_reset_at(captured_text)
    fallback = (datetime.now(timezone.utc) + timedelta(hours=5)).isoformat(timespec="seconds")
    resets_at = parsed or fallback
    fd = _open_state_locked()
    try:
        state = _read_state(fd)
        if profile_id in state:
            state[profile_id]["limit_resets_at"] = resets_at
            state[profile_id]["limit_last_seen_at"] = _now_iso()
            state[profile_id]["limit_last_message"] = captured_text[:300]
            _write_state(fd, state)
    finally:
        _close_state(fd)
    sys.stderr.write(
        f"[claude-pool] {profile_id} marked rate-limited until {resets_at} "
        f"(parsed={'yes' if parsed else 'fallback-+5h'})\n"
    )


def _run_one_dispatch(picked_id: str, picked_home: str,
                      claude_args: list[str]) -> tuple[int, str]:
    """Exec claude under HOME=picked_home. Tee its stdout+stderr through
    our parent streams (so users still see live output) AND capture into
    a buffer so we can scan for rate-limit patterns afterwards.

    Returns (rc, captured_text).
    """
    env = dict(os.environ)
    env["HOME"] = picked_home
    parts = [d for d in (env.get("PATH") or "").split(":")
             if d and Path(d).resolve() != SHIM_DIR.resolve()]
    env["PATH"] = ":".join(parts)
    real = _resolve_real_claude()

    captured_lines: list[str] = []
    proc = subprocess.Popen(
        [real] + (claude_args or []),
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        bufsize=1,
        text=True,
    )

    import threading
    def _pump(src, dst, label):
        try:
            for line in iter(src.readline, ""):
                if not line:
                    break
                dst.write(line)
                dst.flush()
                # Cap captured at ~64KB to avoid pathological RAM use
                if sum(len(x) for x in captured_lines) < 65536:
                    captured_lines.append(line)
        except Exception:
            pass
    t_out = threading.Thread(target=_pump, args=(proc.stdout, sys.stdout, "out"), daemon=True)
    t_err = threading.Thread(target=_pump, args=(proc.stderr, sys.stderr, "err"), daemon=True)
    t_out.start(); t_err.start()
    rc = proc.wait()
    t_out.join(timeout=2); t_err.join(timeout=2)
    return rc, "".join(captured_lines)


def _looks_rate_limited(text: str) -> bool:
    return any(p.search(text or "") for p in _RATE_LIMIT_PATTERNS)


def _claim_profile(picked: dict) -> None:
    """Mark a picked profile as in-use under lock."""
    fd = _open_state_locked()
    try:
        state = _read_state(fd)
        if picked["id"] in state:
            entry = state[picked["id"]]
            entry["in_use"] = entry.get("in_use", 0) + 1
            entry["last_used_at"] = _now_iso()
            entry["total_uses"] = entry.get("total_uses", 0) + 1
            _write_state(fd, state)
    finally:
        _close_state(fd)


def _release_profile(profile_id: str) -> None:
    fd = _open_state_locked()
    try:
        state = _read_state(fd)
        if profile_id in state:
            state[profile_id]["in_use"] = max(0, state[profile_id].get("in_use", 1) - 1)
            _write_state(fd, state)
    finally:
        _close_state(fd)


# Max number of profiles we'll try in one exec call before giving up.
# Defaults to 4 — covers up to 4 distinct accounts; raise via env if needed.
MAX_FAILOVERS = int(os.environ.get("CLAUDE_POOL_MAX_FAILOVERS", "4"))


def cmd_exec(args) -> None:
    """Pick a profile, exec claude. On rate-limit, mark the profile and
    fail over to a different profile (up to MAX_FAILOVERS times). Returns
    the final claude exit code."""
    tried: set[str] = set()
    last_rc = 1
    last_captured = ""

    for attempt in range(MAX_FAILOVERS):
        # Pick under lock
        fd = _open_state_locked()
        try:
            state = _read_state(fd)
            picked = _pick_profile(state, exclude_ids=tried)
        finally:
            _close_state(fd)

        if picked is None:
            if attempt == 0:
                # No profile EVER picked — none authenticated or all rate-limited
                sys.stderr.write(
                    "[claude-pool] No usable profiles. Either none are authenticated "
                    "yet (run `claude-pool init --count N` and follow the login prompts), "
                    "OR every profile is currently rate-limited (run `claude-pool status` "
                    "to see when each resets).\n"
                )
                sys.exit(70)
            # Exhausted all profiles via failover; surface last result
            sys.stderr.write(
                f"[claude-pool] all {len(tried)} authed profile(s) hit rate limit "
                f"this call; surfacing rc={last_rc} from last attempt\n"
            )
            sys.exit(last_rc)

        _claim_profile(picked)
        picked_id = picked["id"]
        tried.add(picked_id)
        sys.stderr.write(
            f"[claude-pool] → {picked_id} (home={picked['home']})"
            f"{' [failover attempt ' + str(attempt + 1) + ']' if attempt else ''}\n"
        )
        try:
            rc, captured = _run_one_dispatch(picked_id, picked["home"], args.claude_args or [])
        finally:
            _release_profile(picked_id)
        last_rc = rc
        last_captured = captured

        # Success → return; we're done
        if rc == 0:
            sys.exit(0)

        # Non-zero exit — check if it's a rate-limit signal we can fail over from
        if _looks_rate_limited(captured):
            _mark_rate_limited(picked_id, captured)
            sys.stderr.write(
                f"[claude-pool] {picked_id} hit rate limit; failing over to next profile\n"
            )
            continue
        # Non-rate-limit failure — surface as-is, no failover (e.g. user
        # cancelled, prompt error, etc.).
        sys.exit(rc)

    # Shouldn't reach here, but propagate the last code
    sys.exit(last_rc)


def cmd_login_help(args) -> None:
    """Print the one-line login command for a specific profile."""
    fd = _open_state_locked()
    try:
        state = _read_state(fd)
    finally:
        _close_state(fd)
    real = _resolve_real_claude()
    target = args.profile
    if target:
        if target not in state:
            print(f"Profile {target} not found. Available: {list(state.keys())}", file=sys.stderr)
            sys.exit(2)
        print(f"HOME={state[target]['home']} {real} /login")
        return
    for k in sorted(state.keys()):
        already = " (authed)" if _is_authenticated(state[k]["home"]) else ""
        print(f"# {k}{already}")
        print(f"HOME={state[k]['home']} {real} /login")
        print()


def cmd_remove(args) -> None:
    """Remove a profile dir + state entry (e.g. when an account is rotated)."""
    fd = _open_state_locked()
    try:
        state = _read_state(fd)
        if args.profile not in state:
            print(f"profile {args.profile} not found", file=sys.stderr)
            sys.exit(2)
        home = state[args.profile].get("home", "")
        if home and Path(home).exists():
            shutil.rmtree(home, ignore_errors=True)
        del state[args.profile]
        _write_state(fd, state)
    finally:
        _close_state(fd)
    print(f"removed {args.profile}")


def main() -> None:
    # Special-case: when invoked with NO subcommand and no args, show help.
    # When invoked as `claude-pool exec -- ...`, treat the rest as claude args.
    p = argparse.ArgumentParser(prog="claude-pool",
                                description="Round-robin Claude Max account multiplexer.")
    sub = p.add_subparsers(dest="cmd", required=True)

    pi = sub.add_parser("init", help="create N profile dirs + print login commands")
    pi.add_argument("--count", "-n", type=int, default=2)
    pi.add_argument("--labels", nargs="+", default=None, help="optional human labels")
    pi.set_defaults(func=cmd_init)

    ps = sub.add_parser("status", help="show profile usage")
    ps.set_defaults(func=cmd_status)

    pe = sub.add_parser("exec", help="exec claude under the next-due profile")
    pe.add_argument("claude_args", nargs=argparse.REMAINDER,
                    help="args after `--` are forwarded to claude verbatim")
    pe.set_defaults(func=cmd_exec)

    pl = sub.add_parser("login-help", help="print HOME=...claude /login command(s)")
    pl.add_argument("--profile", default=None, help="specific profile (else all)")
    pl.set_defaults(func=cmd_login_help)

    pr = sub.add_parser("remove", help="remove a profile (deletes its dir)")
    pr.add_argument("profile")
    pr.set_defaults(func=cmd_remove)

    args = p.parse_args()
    # When `exec`'s claude_args starts with `--`, drop it
    if args.cmd == "exec" and args.claude_args and args.claude_args[0] == "--":
        args.claude_args = args.claude_args[1:]
    args.func(args)


if __name__ == "__main__":
    main()
