#!/usr/bin/env python3
"""claude-pool — round-robin / least-busy multiplexer across multiple
Claude Max accounts.

Each account gets its own isolated profile dir under
$CLAUDE_POOL_ROOT/profile-<N>/. When `claude-pool exec` runs, it picks the
next-due profile and execs `claude` with HOME pointed at that dir, so all
of claude's auth state (.claude/.credentials.json + .claude.json) reads
from THAT account's profile.

Subcommands:
  init [--count N] [--labels ...]
      Create N profile dirs + print login instructions. Idempotent —
      re-running doesn't blow away existing profiles.

  status
      Show each profile's auth state, in-use count, total uses, last
      used timestamp.

  exec -- [claude args...]
      Pick the next-due profile (least in-use, then oldest last-used)
      and exec claude with that profile's HOME. Forwards stdin/stdout
      and the exit code.

Wiring agents:
  Put $CLAUDE_POOL_ROOT/bin/ first on PATH (the init step writes a
  `claude` shim there that delegates to `claude-pool exec`). Existing
  agent code that calls `claude --print ...` automatically routes
  through the pool with zero code changes.

Environment overrides:
  CLAUDE_POOL_ROOT       — base dir (default: ~/.reusable-agents/claude-pool)
  CLAUDE_POOL_REAL_CLAUDE — path to the real claude binary (auto-detected
                            from PATH when unset, excluding the shim)
"""
from __future__ import annotations

import argparse
import fcntl
import json
import os
import shutil
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(os.environ.get("CLAUDE_POOL_ROOT")
            or os.path.expanduser("~/.reusable-agents/claude-pool"))
STATE_FILE = ROOT / "state.json"
SHIM_DIR = ROOT / "bin"
SHIM_PATH = SHIM_DIR / "claude"


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _resolve_real_claude() -> str:
    """Find the real claude binary (not our shim)."""
    explicit = os.environ.get("CLAUDE_POOL_REAL_CLAUDE")
    if explicit and Path(explicit).is_file():
        return explicit
    shim_resolved = SHIM_PATH.resolve() if SHIM_PATH.exists() else None
    for d in (os.environ.get("PATH") or "").split(":"):
        if not d:
            continue
        cand = Path(d) / "claude"
        if not cand.is_file():
            continue
        try:
            if shim_resolved and cand.resolve() == shim_resolved:
                continue
        except Exception:
            pass
        return str(cand)
    raise SystemExit("claude binary not found on PATH (set CLAUDE_POOL_REAL_CLAUDE)")


def _open_state_locked():
    """Open state.json with an exclusive flock. Caller must close + unlock."""
    ROOT.mkdir(parents=True, exist_ok=True)
    fd = os.open(str(STATE_FILE), os.O_RDWR | os.O_CREAT, 0o644)
    fcntl.flock(fd, fcntl.LOCK_EX)
    return fd


def _read_state(fd: int) -> dict:
    try:
        raw = os.pread(fd, 1 << 20, 0).decode() or "{}"
        return json.loads(raw)
    except Exception:
        return {}


def _write_state(fd: int, state: dict) -> None:
    blob = json.dumps(state, indent=2).encode()
    os.ftruncate(fd, 0)
    os.pwrite(fd, blob, 0)


def _close_state(fd: int) -> None:
    try:
        fcntl.flock(fd, fcntl.LOCK_UN)
    finally:
        os.close(fd)


def _is_authenticated(home: str) -> bool:
    return (Path(home) / ".claude" / ".credentials.json").exists()


def _ensure_profile_dir(idx: int, label: str = "") -> Path:
    pdir = ROOT / f"profile-{idx}"
    pdir.mkdir(parents=True, exist_ok=True)
    # Symlink read-mostly user configs so claude's tool calls (git, etc.)
    # see the same identity. We isolate ONLY the Claude auth state.
    real_home = Path(os.path.expanduser("~"))
    for fname in (".gitconfig", ".gitignore_global", ".npmrc", ".bashrc"):
        src = real_home / fname
        dst = pdir / fname
        if src.exists() and not dst.exists() and not dst.is_symlink():
            try:
                dst.symlink_to(src)
            except OSError:
                pass
    return pdir


def _write_shim() -> None:
    """Write a `claude` shim that delegates to `claude-pool exec`. Put
    its parent on PATH ahead of /usr/local/bin/claude to route every
    `claude` call through the pool."""
    SHIM_DIR.mkdir(parents=True, exist_ok=True)
    real = _resolve_real_claude()
    SHIM_PATH.write_text(f"""#!/usr/bin/env bash
# Auto-generated by claude-pool. Routes `claude` calls through the pool.
# Real claude binary: {real}
exec python3 {Path(__file__).resolve()} exec -- "$@"
""")
    SHIM_PATH.chmod(0o755)


# ── Subcommands ──────────────────────────────────────────────────────────

def cmd_init(args) -> None:
    n = args.count
    if n < 1:
        raise SystemExit("--count must be ≥ 1")
    fd = _open_state_locked()
    try:
        state = _read_state(fd)
        for i in range(1, n + 1):
            pdir = _ensure_profile_dir(i)
            key = f"profile-{i}"
            label = ""
            if args.labels and i <= len(args.labels):
                label = args.labels[i - 1]
            state.setdefault(key, {})
            state[key].update({
                "id": key,
                "home": str(pdir),
                "in_use": state[key].get("in_use", 0),
                "last_used_at": state[key].get("last_used_at", ""),
                "total_uses": state[key].get("total_uses", 0),
                "label": label or state[key].get("label", ""),
            })
            state[key]["authenticated"] = _is_authenticated(str(pdir))
        _write_state(fd, state)
    finally:
        _close_state(fd)
    _write_shim()
    print(f"\n✓ {n} profile(s) prepared at {ROOT}/")
    print(f"✓ shim written to {SHIM_PATH}\n")
    print(f"To use the pool, prepend its bin/ on PATH:")
    print(f"  export PATH={SHIM_DIR}:$PATH\n")
    print("─" * 70)
    print("To authenticate each profile, run these one-by-one in a terminal")
    print("with browser access (each opens a Claude OAuth flow in your browser):\n")
    for i in range(1, n + 1):
        pdir = ROOT / f"profile-{i}"
        already = "✓ AUTHED" if _is_authenticated(str(pdir)) else "  needs auth"
        real = _resolve_real_claude()
        print(f"  [{already}]  HOME={pdir} {real} /login")
    print("\nAfter logging in to each profile, run:  claude-pool status")
    print("─" * 70)


def cmd_status(args) -> None:
    fd = _open_state_locked()
    try:
        state = _read_state(fd)
        # Refresh authenticated flag from disk
        for p in state.values():
            p["authenticated"] = _is_authenticated(p.get("home", ""))
        _write_state(fd, state)
    finally:
        _close_state(fd)
    if not state:
        print("No profiles configured. Run: claude-pool init --count N")
        return
    print(f"{'PROFILE':<12}  {'AUTH':<5} {'IN_USE':<7} {'TOTAL':<6} {'LAST_USED':<22}  LABEL")
    print("-" * 80)
    for k in sorted(state.keys()):
        p = state[k]
        auth = "✓" if p.get("authenticated") else "—"
        last = p.get("last_used_at") or "-"
        print(f"{p['id']:<12}  {auth:<5} {p.get('in_use',0):<7} {p.get('total_uses',0):<6} {last:<22}  {p.get('label','')}")


def _pick_profile(state: dict) -> dict | None:
    eligible = [
        p for p in state.values()
        if _is_authenticated(p.get("home", ""))
    ]
    if not eligible:
        return None
    eligible.sort(key=lambda p: (p.get("in_use", 0),
                                 p.get("last_used_at", ""),
                                 p.get("id", "")))
    return eligible[0]


def cmd_exec(args) -> None:
    """Pick a profile, exec claude under its HOME, decrement in_use on exit."""
    fd = _open_state_locked()
    try:
        state = _read_state(fd)
        picked = _pick_profile(state)
        if picked is None:
            sys.stderr.write(
                "[claude-pool] No authenticated profiles. Run:\n"
                "  claude-pool init --count <N>\n"
                "Then follow the printed login instructions.\n"
            )
            sys.exit(70)
        picked["in_use"] = picked.get("in_use", 0) + 1
        picked["last_used_at"] = _now_iso()
        picked["total_uses"] = picked.get("total_uses", 0) + 1
        state[picked["id"]] = picked
        _write_state(fd, state)
        picked_id = picked["id"]
        picked_home = picked["home"]
    finally:
        _close_state(fd)

    sys.stderr.write(f"[claude-pool] → {picked_id} (home={picked_home})\n")
    env = dict(os.environ)
    env["HOME"] = picked_home
    # Don't let the shim recurse — strip our bin/ from PATH for the child
    parts = [d for d in (env.get("PATH") or "").split(":") if d and Path(d).resolve() != SHIM_DIR.resolve()]
    env["PATH"] = ":".join(parts)
    real = _resolve_real_claude()
    rc = 1
    try:
        rc = subprocess.call([real] + (args.claude_args or []), env=env)
    finally:
        # Decrement in_use under lock
        fd = _open_state_locked()
        try:
            state = _read_state(fd)
            if picked_id in state:
                state[picked_id]["in_use"] = max(0, state[picked_id].get("in_use", 1) - 1)
                _write_state(fd, state)
        finally:
            _close_state(fd)
    sys.exit(rc)


def cmd_login_help(args) -> None:
    """Print the one-line login command for a specific profile."""
    fd = _open_state_locked()
    try:
        state = _read_state(fd)
    finally:
        _close_state(fd)
    real = _resolve_real_claude()
    target = args.profile
    if target:
        if target not in state:
            print(f"Profile {target} not found. Available: {list(state.keys())}", file=sys.stderr)
            sys.exit(2)
        print(f"HOME={state[target]['home']} {real} /login")
        return
    for k in sorted(state.keys()):
        already = " (authed)" if _is_authenticated(state[k]["home"]) else ""
        print(f"# {k}{already}")
        print(f"HOME={state[k]['home']} {real} /login")
        print()


def cmd_remove(args) -> None:
    """Remove a profile dir + state entry (e.g. when an account is rotated)."""
    fd = _open_state_locked()
    try:
        state = _read_state(fd)
        if args.profile not in state:
            print(f"profile {args.profile} not found", file=sys.stderr)
            sys.exit(2)
        home = state[args.profile].get("home", "")
        if home and Path(home).exists():
            shutil.rmtree(home, ignore_errors=True)
        del state[args.profile]
        _write_state(fd, state)
    finally:
        _close_state(fd)
    print(f"removed {args.profile}")


def main() -> None:
    # Special-case: when invoked with NO subcommand and no args, show help.
    # When invoked as `claude-pool exec -- ...`, treat the rest as claude args.
    p = argparse.ArgumentParser(prog="claude-pool",
                                description="Round-robin Claude Max account multiplexer.")
    sub = p.add_subparsers(dest="cmd", required=True)

    pi = sub.add_parser("init", help="create N profile dirs + print login commands")
    pi.add_argument("--count", "-n", type=int, default=2)
    pi.add_argument("--labels", nargs="+", default=None, help="optional human labels")
    pi.set_defaults(func=cmd_init)

    ps = sub.add_parser("status", help="show profile usage")
    ps.set_defaults(func=cmd_status)

    pe = sub.add_parser("exec", help="exec claude under the next-due profile")
    pe.add_argument("claude_args", nargs=argparse.REMAINDER,
                    help="args after `--` are forwarded to claude verbatim")
    pe.set_defaults(func=cmd_exec)

    pl = sub.add_parser("login-help", help="print HOME=...claude /login command(s)")
    pl.add_argument("--profile", default=None, help="specific profile (else all)")
    pl.set_defaults(func=cmd_login_help)

    pr = sub.add_parser("remove", help="remove a profile (deletes its dir)")
    pr.add_argument("profile")
    pr.set_defaults(func=cmd_remove)

    args = p.parse_args()
    # When `exec`'s claude_args starts with `--`, drop it
    if args.cmd == "exec" and args.claude_args and args.claude_args[0] == "--":
        args.claude_args = args.claude_args[1:]
    args.func(args)


if __name__ == "__main__":
    main()
